import { test, expect } from '@playwright/test';

test.describe('AI Suggestions', () => {
  test('should fetch and display pending AI suggestions generated by the AI Manager', async ({ page }) => {
    await page.goto('/');
    const suggestionsPanel = page.getByRole('region', { name: 'AI Suggestions' });
    await expect(suggestionsPanel).toBeVisible();
    
    const suggestionItem = suggestionsPanel.getByRole('listitem').first();
    await expect(suggestionItem).toBeVisible();
  });

  test('should accept an AI suggestion and apply the proposed changes (e.g., task creation)', async ({ page }) => {
    await page.goto('/');
    const suggestionItem = page.getByRole('listitem').filter({ hasText: 'Suggested Task: Gym' });
    await suggestionItem.getByRole('button', { name: 'Accept' }).click();
    
    await expect(page.getByText('Suggested Task: Gym')).not.toBeVisible();
    await expect(page.getByRole('listitem').filter({ hasText: 'Gym' })).toBeVisible();
  });

  test('should reject an AI suggestion, remove it from the list, and update status to rejected', async ({ page }) => {
    await page.goto('/');
    const suggestionItem = page.getByRole('listitem').filter({ hasText: 'Suggested Task: Read' });
    await suggestionItem.getByRole('button', { name: 'Reject' }).click();
    
    await expect(page.getByText('Suggested Task: Read')).not.toBeVisible();
  });

  test('should correctly render the context, type, and rationale of an AI suggestion', async ({ page }) => {
    await page.goto('/');
    const suggestionItem = page.getByRole('listitem').filter({ hasText: 'Reschedule Meeting' });
    
    await expect(suggestionItem.getByText('Type: Reschedule')).toBeVisible();
    await expect(suggestionItem.getByText('Rationale:')).toBeVisible();
  });

  test('should clear the suggestions UI section when all pending items have been resolved', async ({ page }) => {
    await page.goto('/');
    // Assuming we clear all suggestions by accepting or rejecting
    const rejectButtons = await page.getByRole('button', { name: 'Reject' }).all();
    for (const btn of rejectButtons) {
      await btn.click();
    }
    
    await expect(page.getByText('No new suggestions')).toBeVisible();
  });
});
